#!/usr/bin/env bash
#This script transfer file to the server
########################################

if [ $# -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path=$1
ip=$2
user=$3
ssh_key_path=$4

scp -o StrictHostkeyChecking=no -i "$ssh_key_path" "$file_path" "$user@$ip:~/"
